# Site settings
title: Nataliia Zdrok
description: AWS cloud practitioner
# baseurl: "" # the subpath of your site, e.g. /blog
url: https://github.com/Nataliia888

# User settings
username: Nataliia Zdrok
user_description: CompTIA Security+ and CompTIA Network+ certified professional currently focusing on AWS deep learning.
user_title: AWS Cloud Practitioner
email: dev.p.zdrok@gmail.com
github_username: Nataliia888
# gplus_username:  lorem_ipsum

exclude: ["package.json", "src", "node_modules"]
